const express = require('express');
const router = express.Router();
const { getSkills, addSkill, deleteSkill } = require('../controllers/skillController');
const { protect, authorize } = require('../middleware/authMiddleware');
router.get('/', getSkills);
router.post('/', protect, authorize('recruiter'), addSkill);
router.delete('/:id', protect, authorize('recruiter'), deleteSkill);
const { getSkills } = require('../controllers/skillController');
router.get('/', getSkills);
module.exports = router;
